#PLEASE READ THE INTRODUCTION CAREFULLY FOR EFFICIENT USE OF INSTA_BOOT

#PASSWORD YOU NEED IN ORDER TO START IS
'''HELLO JARVIS'''

#JARVIS IS YOUR PERSONAL ASSISTANT
#THIS APP HELPS YOU TO FETCH USER DETAILS, LIKE A POST ,COMMENT ON A POST AND MANY MORE


'''THE APP CONVERS ALL THE MANDATORY OBJECTIVES AS WELL AS ALL THE EXTRA OBJECTIVES
THE USER HAVE TO ENTER RIGHT INFORMATION TO USE THE APP
ALWAYS ENTER INTERGER WHERE IT IS ASKED ...
ENTERING ANY OTHER DATATYPE WILL GENERATE THE UNWANTED TERMINATION OF APP
'''



#IMPORTING LIBRARY/FILE IN ORDER TO USE THEM
from instabot import start_choice
from termcolor import colored


while True:

    #ASKING FOR PASSWORD.....NOTHING WILL APPEAR ON CONSOLE UNLESS YOU ENTER HELLO JARVIS
    password=raw_input()
    if password.upper()=="HELLO JARVIS":
        print colored("GOOD MORNING MR.SAHIL. GLAD TO HAVE YOU BACK. I WAS EAGERLY WAITING FOR YOU SIR",'green')

        #CALLING MAIN FUNCTION FROM WHERE THE ACTUAL PROGRAM STARTS
        start_choice()